MAID-2151: Reconnect remote logger if it's disconnected
maidsafe/maidsafe_utilities pull request #113
Opened 2017-07-25 06:16 UTC by michaelsproul

2017-07-25 14:56 UTC, ustulation requested changes

2017-07-25 14:56 UTC, ustulation commented on test/src/bin/ws_server.rs
> +    }).unwrap();
we only use `unwrap!()` macro from the unwrap crate

2017-07-25 14:56 UTC, ustulation commented on test/src/main.rs
> +    // FIXME: remove the stuff I added.
Why is this commnent there

2017-07-25 16:53 UTC, ustulation requested changes

2017-07-25 16:53 UTC, ustulation commented on .gitignore
> -bin/
why delete this ?

2017-07-26 01:00 UTC, michaelsproul commented on .gitignore
> -bin/
I think it's out-dated. Cargo doesn't generate files in directories called `bin` any more, and this rule was leading to `test/src/bin/ws_server.rs` being excluded.

2017-07-26 05:57 UTC, michaelsproul commented on test/src/main.rs
> +    // FIXME: remove the stuff I added.
to force me to write a better test 😁 (and delete this comment before merging)

2017-07-26 11:14 UTC, ustulation approved these changes

2017-07-26 11:14 UTC, merged