Remove SipHash, add SHA3
maidsafe/maidsafe_utilities pull request #81
Opened 2017-02-24 06:39 UTC by michaelsproul

2017-03-01 06:30 UTC, michaelsproul commented
Plan of action, to be implemented by me, soon...

* Don't put `sha3` in this crate (yet), but *do* remove SipHash (no urgency to re-release).
* Put the necessary `sha3` stuff in `routing` for now, and depend on that from `safe_vault`.
* Later: assess hash function usage and consider using SHA2/3 everywhere with multihash.

2017-03-10 12:39 UTC, ustulation commented
@michaelsproul So i guess this is no longer needed - could be submit a PR then to get rid of sip-hasher thingy from utilities ? You can close this one if you want or make this the PR with the changes to just remove sip hasher.

2017-03-12 02:45 UTC, michaelsproul commented
I've updated this PR to just remove SipHash, the only remaining mention of sha3 is the branch name.

2017-03-13 11:26 UTC, ustulation requested changes

2017-03-13 11:26 UTC, ustulation commented on src/lib.rs
> +#[cfg_attr(test, macro_use)]
Why is this change needed ? (Is it something to do with the treatment of macros in newer rusts ? )

(On a side note: Pls rebase against latest master - should be good to merge after that)

2017-03-14 01:47 UTC, michaelsproul commented on src/lib.rs
> +#[cfg_attr(test, macro_use)]
Yeah, I've been trying out Rust's new incremental compilation, and the new compiler is smart enough to know that the macros are only used in tests.

2017-03-14 01:50 UTC, michaelsproul commented on src/lib.rs
> +#[cfg_attr(test, macro_use)]
(rebased onto master)

2017-03-15 09:41 UTC, michaelsproul commented on src/lib.rs
> +#[cfg_attr(test, macro_use)]
ready to go @ustulation, although safe_vault will break if we release a new version without merging https://github.com/maidsafe/safe_vault/pull/606 (which depends on routing master, or a new version)

2017-03-24 10:06 UTC, ustulation approved these changes

2017-03-24 10:13 UTC, merged